import { SVGMotionProps } from 'framer-motion';
import {
    AI,
    AVI,
    BMP,
    CRD,
    CSV,
    DLL,
    DOC,
    DOCX,
    DWG,
    EPS,
    FLV,
    GIFF,
    HTML,
    ISO,
    JAVA,
    JPG,
    MDB,
    MID,
    MOV,
    MP3,
    MP4,
    MPEG,
    PDF,
    PNG,
    PPT,
    PS,
    PSD,
    PUB,
    RAR,
    RAW,
    RSS,
    SVG,
    TIFF,
    TXT,
    WAV,
    WMA,
    XML,
    XSL,
    ZIP,
} from './index';

export const extensionIcons: { [key: string]: SVGMotionProps<SVGSVGElement> & React.ReactNode } = {
    ai: <AI style={{ width: '32px', height: '32px' }} />,
    avi: <AVI style={{ width: '32px', height: '32px' }} />,
    bmp: <BMP style={{ width: '32px', height: '32px' }} />,
    crd: <CRD style={{ width: '32px', height: '32px' }} />,
    csv: <CSV style={{ width: '32px', height: '32px' }} />,
    dll: <DLL style={{ width: '32px', height: '32px' }} />,
    doc: <DOC style={{ width: '32px', height: '32px' }} />,
    docx: <DOCX style={{ width: '32px', height: '32px' }} />,
    dwg: <DWG style={{ width: '32px', height: '32px' }} />,
    eps: <EPS style={{ width: '32px', height: '32px' }} />,
    flv: <FLV style={{ width: '32px', height: '32px' }} />,
    giff: <GIFF style={{ width: '32px', height: '32px' }} />,
    html: <HTML style={{ width: '32px', height: '32px' }} />,
    iso: <ISO style={{ width: '32px', height: '32px' }} />,
    java: <JAVA style={{ width: '32px', height: '32px' }} />,
    jpg: <JPG style={{ width: '32px', height: '32px' }} />,
    mdb: <MDB style={{ width: '32px', height: '32px' }} />,
    mid: <MID style={{ width: '32px', height: '32px' }} />,
    mov: <MOV style={{ width: '32px', height: '32px' }} />,
    mp3: <MP3 style={{ width: '32px', height: '32px' }} />,
    mp4: <MP4 style={{ width: '32px', height: '32px' }} />,
    mpeg: <MPEG style={{ width: '32px', height: '32px' }} />,
    pdf: <PDF style={{ width: '32px', height: '32px' }} />,
    png: <PNG style={{ width: '32px', height: '32px' }} />,
    ppt: <PPT style={{ width: '32px', height: '32px' }} />,
    ps: <PS style={{ width: '32px', height: '32px' }} />,
    psd: <PSD style={{ width: '32px', height: '32px' }} />,
    pub: <PUB style={{ width: '32px', height: '32px' }} />,
    rar: <RAR style={{ width: '32px', height: '32px' }} />,
    raw: <RAW style={{ width: '32px', height: '32px' }} />,
    rss: <RSS style={{ width: '32px', height: '32px' }} />,
    svg: <SVG style={{ width: '32px', height: '32px' }} />,
    tiff: <TIFF style={{ width: '32px', height: '32px' }} />,
    txt: <TXT style={{ width: '32px', height: '32px' }} />,
    wav: <WAV style={{ width: '32px', height: '32px' }} />,
    wma: <WMA style={{ width: '32px', height: '32px' }} />,
    xml: <XML style={{ width: '32px', height: '32px' }} />,
    xls: <XSL style={{ width: '32px', height: '32px' }} />,
    xlsx: <XSL style={{ width: '32px', height: '32px' }} />,
    zip: <ZIP style={{ width: '32px', height: '32px' }} />,
};
